services:

  db:
    image: postgres:15.2
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: [ "./wait-for-it.sh", "db:5432", "--",
               "/bin/sh", "/code/pre-launch-operations.sh"]
    restart: always
    volumes:
      - static:/code/ctracker/static
      - media:/code/ctracker/media
    environment:
      - DJANGO_SETTINGS_MODULE=ctracker.settings.dev
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  nginx:
    image: nginx:1.23.4
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - static:/static
      - media:/media
      - ./ctracker/ssl:/ssl
    ports:
      - "80:80"
      - "443:443"

volumes:
  static:
  media:
  postgres_db:
