x-common-variables: &common-variables
  DJANGO_SETTINGS_MODULE: ctracker.settings.prod
  POSTGRES_DB: {{ env.POSTGRES_DB }}
  POSTGRES_USER: {{ env.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ env.POSTGRES_PASSWORD }}
  POSTGRES_HOST: {{ env.POSTGRES_HOST }}
  POSTGRES_PORT: {{ env.POSTGRES_PORT }}
  DJANGO_SECRET_KEY: {{ env.DJANGO_SECRET_KEY }}
  TG_BOT_API_KEY: {{ env.TG_BOT_API_KEY }}
  CELERY_BROKER: {{ env.CELERY_BROKER }}
  CELERY_BACKEND: {{ env.CELERY_BACKEND }}

services:
  db:
    image: postgres:15.2
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment: *common-variables

  redis:
    image: redis:7-alpine

  web:
    image: {{ env.IMAGE_URL }}
    command: /start.sh
    restart: always
    volumes:
      - nginx:/code/data/nginx
      - ctracker_static:/code/ctracker/static
      - ctracker_media:/code/ctracker/media
    environment: *common-variables
    depends_on:
      - db

  nginx:
    image: nginx:1.23.4
    restart: always
    volumes:
      - nginx:/etc/nginx/templates
      - ctracker_static:/static
      - ctracker_media:/media
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - ystep_root:/ystep
    ports:
      - "80:80"
      - "443:443"

  celery_worker:
    image: {{ env.IMAGE_URL }}
    command: /start-celeryworker.sh
    environment: *common-variables
    depends_on:
      - redis
      - db

  celery_beat:
    image: {{ env.IMAGE_URL }}
    command: /start-celerybeat.sh
    environment: *common-variables
    depends_on:
      - redis
      - db

  telegram_bot:
    image: {{ env.IMAGE_URL }}
    command: /start-telegrambot.sh
    environment: *common-variables
    depends_on:
      - redis
      - db

  flower:
    image: {{ env.IMAGE_URL }}
    command: /start-flower.sh
    environment: *common-variables
    depends_on:
      - redis
      - db
      - celery_worker

volumes:
  nginx:
  postgres_db:
  ctracker_static:
  ctracker_media:
  certbot_conf:
  certbot_www:
  ystep_root:
