services:

  db:
    image: postgres:15.2
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB={{ env.POSTGRES_DB }}
      - POSTGRES_USER={{ env.POSTGRES_USER }}
      - POSTGRES_PASSWORD={{ env.POSTGRES_PASSWORD }}

  web:
    image: {{ env.IMAGE_URL }}
    command: [ "./wait-for-it.sh", "db:5432", "--",
               "pre-launch-operations.sh"]
    restart: always
    volumes:
      - nginx_config:/code/config/nginx
      - application:/code
    environment:
      - DJANGO_SETTINGS_MODULE=ctracker.settings.prod
      - POSTGRES_DB={{ env.POSTGRES_DB }}
      - POSTGRES_USER={{ env.POSTGRES_USER }}
      - POSTGRES_PASSWORD={{ env.POSTGRES_PASSWORD }}
      - DJANGO_SECRET_KEY= {{ env.DJANGO_SECRET_KEY }}
    depends_on:
      - db

  nginx:
    image: nginx:1.23.4
    restart: always
    volumes:
      - nginx_config:/etc/nginx/templates
      - application:/code
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_db:
  nginx_config:
  application:
