services:

  db:
    image: postgres:15.2
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    #command: python /code/ctracker/manage.py runserver 0.0.0.0:8000
    #    command: [ "./wait-for-it.sh", "db:5432", "--",
    #               "python", "/code/ctracker/manage.py", "runserver",
    #               "0.0.0.0:8000" ]
    command: [ "./wait-for-it.sh", "db:5432", "--",
               "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini" ]
    restart: always
    volumes:
      - .:/code
    #    ports:
    #      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=ctracker.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  nginx:
    image: nginx:1.23.4
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"
      - "443:443"