# Generated by Django 4.1.5 on 2023-03-29 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description_short', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'assembly',
                'verbose_name_plural': 'assemblies',
                'db_table': 'assembly',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembly.assembly')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_components', to='product.product')),
            ],
            options={
                'verbose_name': 'assembly component',
                'verbose_name_plural': 'assembly components',
                'db_table': 'assembly_component',
            },
        ),
        migrations.AddField(
            model_name='assembly',
            name='component',
            field=models.ManyToManyField(blank=True, related_name='contains', through='assembly.AssemblyComponent', to='product.product'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owns_assemblies', to=settings.AUTH_USER_MODEL),
        ),
    ]
