# Generated by Django 4.1.5 on 2023-11-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_allow_notifications_profile_telegram_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_verification_code',
            field=models.IntegerField(default=0, verbose_name='Код проверки Telegram'),
        ),
    ]
