# Generated by Django 4.1.5 on 2023-03-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_description_short_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationvalue',
            name='value',
            field=models.CharField(max_length=400),
        ),
    ]
