# Generated by Django 4.1.5 on 2023-04-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_subscriptions_alter_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
