# Generated by Django 4.1.5 on 2023-11-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productgroup_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilter',
            name='display_widget',
            field=models.CharField(choices=[('CHOICE', 'MultipleChoice'), ('RANGE', 'Range')], default='CHOICE', max_length=10),
        ),
    ]
